import charaImg from "../assets/izumi.gif";
import wallImg from "../assets/room/wall.png";
import wallLv1Img from "../assets/room/wall_lv1.png";
import floorImg from "../assets/room/floor.png";
import floorTileImg from "../assets/room/floor1.png";
import floorGreyImg from "../assets/room/floor_grey_2.png";
import bedImg from "../assets/furniture/bed_pink.png";
import bookshelfImg from "../assets/furniture/bookshelf.png";
import clockImg from "../assets/furniture/clock.png";
import fanImg from "../assets/furniture/fan.png";
import bulletinBoardImg from "../assets/furniture/keijibann.png";
import gameCabinetImg from "../assets/furniture/game-cabinet.png";
import questBoardImg from "../assets/furniture/quest-board.png";
import officeChairImg from "../assets/furniture/office_chair.png";
import roundTableImg from "../assets/furniture/round_table.png";
import cactusImg from "../assets/furniture/saboten.png";
import floweringCactusImg from "../assets/furniture/sabowithflower.png";
import shelfImg from "../assets/furniture/shelf.png";
import sofaImg from "../assets/furniture/sofa.png";
import sunflowerImg from "../assets/furniture/sunflower.png";
import stoveImg from "../assets/furniture/suto-bu.png";
import windowImg from "../assets/furniture/window.png";
import retroTVImg from "../assets/furniture/retro_tv.png";

export const SHOW_GRID = false;

export const roomGrids = {
  wall: {
    cols: 12,
    rows: 4,
  },
  floor: {
    cols: 12,
    rows: 8,
  },
};

export const tileTextures = {
  labWall: wallLv1Img,
  westernWall: wallImg,
  labFloor: floorGreyImg,
  westernFloor: floorImg,
  tileFloor: floorTileImg,
};

export const defaultRoomTheme = {
  wall: "labWall",
  floor: "labFloor",
};

export const wallTextureOptions = [
  { id: "labWall", name: "研究室", minLevel: 1 },
  { id: "westernWall", name: "洋風", minLevel: 2 },
];

export const floorTextureOptions = [
  { id: "labFloor", name: "研究室", minLevel: 1 },
  { id: "westernFloor", name: "洋風", minLevel: 2 },
  { id: "tileFloor", name: "タイル", minLevel: 2 },
];

export const roomItems = [
  {
    id: "round_table",
    name: "Round Table",
    price: 50,
    category: "lab",
    surface: "floor",
    minLevel: 1,
    src: roundTableImg,
    alt: "round table",
    col: 5,
    row: 5,
    colSpan: 3,
    rowSpan: 2,
    z: 7,
    anchor: "bottomLeft",
  },
  {
    id: "office_chair",
    name: "Office Chair",
    price: 35,
    category: "lab",
    surface: "floor",
    minLevel: 1,
    src: officeChairImg,
    alt: "office chair",
    col: 4,
    row: 4,
    colSpan: 1.5,
    rowSpan: 2.5,
    z: 6,
    anchor: "bottomLeft",
  },
  {
    id: "bulletin_board",
    name: "Bulletin Board",
    price: 50,
    category: "lab",
    surface: "wall",
    minLevel: 1,
    src: bulletinBoardImg,
    alt: "bulletin board",
    col: 2,
    row: 1,
    colSpan: 3,
    rowSpan: 3,
    z: 7,
    anchor: "bottomLeft",
  },
  {
    id: "quest_board",
    name: "Quest Board",
    price: 50,
    category: "lab",
    surface: "floor",
    minLevel: 1,
    src: questBoardImg,
    alt: "quest board",
    col: 7,
    row: 8,
    colSpan: 3,
    rowSpan: 4,
    z: 8,
    anchor: "bottomLeft",
  },
  {
    id: "window",
    name: "Window",
    price: 30,
    category: "western",
    surface: "wall",
    minLevel: 2,
    src: windowImg,
    alt: "window",
    col: 8,
    row: 2,
    colSpan: 2,
    rowSpan: 2,
    z: 6,
    anchor: "bottomLeft",
  },
  {
    id: "clock",
    name: "Clock",
    price: 30,
    category: "western",
    surface: "wall",
    minLevel: 2,
    src: clockImg,
    alt: "clock",
    col: 11,
    row: 1,
    colSpan: 1,
    rowSpan: 1,
    z: 7,
    anchor: "bottomLeft",
  },
  {
    id: "stove",
    name: "Stove",
    price: 50,
    category: "western",
    surface: "wall",
    minLevel: 2,
    src: stoveImg,
    alt: "stove",
    col: 5,
    row: 3,
    colSpan: 2,
    rowSpan: 3,
    z: 7,
    anchor: "bottomLeft",
  },
  {
    id: "bookshelf",
    name: "Bookshelf",
    price: 80,
    category: "western",
    surface: "floor",
    minLevel: 3,
    src: bookshelfImg,
    alt: "bookshelf",
    col: 2,
    row: 1,
    colSpan: 2,
    rowSpan: 3,
    z: 8,
    className: "roomBookshelf",
    anchor: "bottomLeft",
  },
  {
    id: "shelf",
    name: "Shelf",
    price: 100,
    category: "western",
    surface: "floor",
    minLevel: 4,
    src: shelfImg,
    alt: "shelf",
    col: 6,
    row: 1,
    colSpan: 2,
    rowSpan: 3,
    z: 8,
    anchor: "bottomLeft",
  },
  {
    id: "bed",
    name: "Bed",
    price: 150,
    category: "western",
    surface: "floor",
    minLevel: 5,
    src: bedImg,
    alt: "bed",
    col: 8,
    row: 3,
    colSpan: 2,
    rowSpan: 2,
    z: 7,
    anchor: "bottomLeft",
  },

  {
  id: "retro_tv",
  name: "Retro TV ",
  price: 80,
  category: "western",
  surface: "floor",
  minLevel: 2,
  src: retroTVImg,
  alt: "retro television",
  col: 7,
  row: 4,
  colSpan: 1,
  rowSpan: 1,
  z: 8,
  anchor: "bottomLeft",
},

  {
    id: "game_cabinet",
    name: "Game Cabinet",
    price: 100,
    category: "lab",
    surface: "floor",
    minLevel: 2,
    src: gameCabinetImg,
    alt: "game cabinet",
    col: 9,
    row: 4,
    colSpan: 2,
    rowSpan: 3,
    z: 9,
    anchor: "bottomLeft",
  },
  {
    id: "fan",
    name: "Fan",
    price: 40,
    category: "western",
    surface: "floor",
    minLevel: 1,
    src: fanImg,
    alt: "electric fan",
    col: 10,
    row: 5,
    colSpan: 1,
    rowSpan: 1,
    z: 8,
    anchor: "bottomLeft",
  },
  {
    id: "cactus",
    name: "Cactus",
    price: 30,
    category: "western",
    surface: "floor",
    minLevel: 1,
    src: cactusImg,
    alt: "cactus",
    col: 2,
    row: 6,
    colSpan: 1,
    rowSpan: 1.3,
    z: 8,
    anchor: "bottomLeft",
  },
  {
    id: "flowering_cactus",
    name: "Flowering Cactus",
    price: 45,
    category: "western",
    surface: "floor",
    minLevel: 2,
    src: floweringCactusImg,
    alt: "flowering cactus",
    col: 3,
    row: 6,
    colSpan: 1,
    rowSpan: 1.3,
    z: 8,
    anchor: "bottomLeft",
  },
  {
    id: "sofa",
    name: "Sofa",
    price: 120,
    category: "western",
    surface: "floor",
    minLevel: 3,
    src: sofaImg,
    alt: "sofa",
    col: 5,
    row: 5,
    colSpan: 2,
    rowSpan: 1.5,
    z: 8,
    anchor: "bottomLeft",
  },
  {
    id: "sunflower",
    name: "Sunflower",
    price: 50,
    category: "western",
    surface: "floor",
    minLevel: 2,
    src: sunflowerImg,
    alt: "sunflower",
    col: 11,
    row: 5,
    colSpan: 1,
    rowSpan: 1.3,
    z: 8,
    anchor: "bottomLeft",
  },
  {
    id: "chara",
    name: "Character",
    surface: "floor",
    minLevel: 1,
    src: charaImg,
    alt: "character",
    col: 6,
    row: 6,
    colSpan: 1.5,
    rowSpan: 1.5,
    z: 10,
    className: "roomChara",
    anchor: "bottomLeft",
    isFixed: true,
  },
  
];

